// Generated by gencpp from file map_mng/GetMapsRequest.msg
// DO NOT EDIT!


#ifndef MAP_MNG_MESSAGE_GETMAPSREQUEST_H
#define MAP_MNG_MESSAGE_GETMAPSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_mng
{
template <class ContainerAllocator>
struct GetMapsRequest_
{
  typedef GetMapsRequest_<ContainerAllocator> Type;

  GetMapsRequest_()
    : key(0)  {
    }
  GetMapsRequest_(const ContainerAllocator& _alloc)
    : key(0)  {
  (void)_alloc;
    }



   typedef int32_t _key_type;
  _key_type key;





  typedef boost::shared_ptr< ::map_mng::GetMapsRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_mng::GetMapsRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapsRequest_

typedef ::map_mng::GetMapsRequest_<std::allocator<void> > GetMapsRequest;

typedef boost::shared_ptr< ::map_mng::GetMapsRequest > GetMapsRequestPtr;
typedef boost::shared_ptr< ::map_mng::GetMapsRequest const> GetMapsRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_mng::GetMapsRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_mng::GetMapsRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::map_mng::GetMapsRequest_<ContainerAllocator1> & lhs, const ::map_mng::GetMapsRequest_<ContainerAllocator2> & rhs)
{
  return lhs.key == rhs.key;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::map_mng::GetMapsRequest_<ContainerAllocator1> & lhs, const ::map_mng::GetMapsRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace map_mng

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::map_mng::GetMapsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_mng::GetMapsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_mng::GetMapsRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_mng::GetMapsRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_mng::GetMapsRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_mng::GetMapsRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_mng::GetMapsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d5f7d6b16cb4e9d7a81b607f04247968";
  }

  static const char* value(const ::map_mng::GetMapsRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd5f7d6b16cb4e9d7ULL;
  static const uint64_t static_value2 = 0xa81b607f04247968ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_mng::GetMapsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_mng/GetMapsRequest";
  }

  static const char* value(const ::map_mng::GetMapsRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_mng::GetMapsRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 key\n"
;
  }

  static const char* value(const ::map_mng::GetMapsRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_mng::GetMapsRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.key);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapsRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_mng::GetMapsRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_mng::GetMapsRequest_<ContainerAllocator>& v)
  {
    s << indent << "key: ";
    Printer<int32_t>::stream(s, indent + "  ", v.key);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MNG_MESSAGE_GETMAPSREQUEST_H
