// Generated by gencpp from file map_mng/GetMaps.msg
// DO NOT EDIT!


#ifndef MAP_MNG_MESSAGE_GETMAPS_H
#define MAP_MNG_MESSAGE_GETMAPS_H

#include <ros/service_traits.h>


#include <map_mng/GetMapsRequest.h>
#include <map_mng/GetMapsResponse.h>


namespace map_mng
{

struct GetMaps
{

typedef GetMapsRequest Request;
typedef GetMapsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetMaps
} // namespace map_mng


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_mng::GetMaps > {
  static const char* value()
  {
    return "7e5e87a0d74c663ed90922f6efddb3e3";
  }

  static const char* value(const ::map_mng::GetMaps&) { return value(); }
};

template<>
struct DataType< ::map_mng::GetMaps > {
  static const char* value()
  {
    return "map_mng/GetMaps";
  }

  static const char* value(const ::map_mng::GetMaps&) { return value(); }
};


// service_traits::MD5Sum< ::map_mng::GetMapsRequest> should match
// service_traits::MD5Sum< ::map_mng::GetMaps >
template<>
struct MD5Sum< ::map_mng::GetMapsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_mng::GetMaps >::value();
  }
  static const char* value(const ::map_mng::GetMapsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_mng::GetMapsRequest> should match
// service_traits::DataType< ::map_mng::GetMaps >
template<>
struct DataType< ::map_mng::GetMapsRequest>
{
  static const char* value()
  {
    return DataType< ::map_mng::GetMaps >::value();
  }
  static const char* value(const ::map_mng::GetMapsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_mng::GetMapsResponse> should match
// service_traits::MD5Sum< ::map_mng::GetMaps >
template<>
struct MD5Sum< ::map_mng::GetMapsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_mng::GetMaps >::value();
  }
  static const char* value(const ::map_mng::GetMapsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_mng::GetMapsResponse> should match
// service_traits::DataType< ::map_mng::GetMaps >
template<>
struct DataType< ::map_mng::GetMapsResponse>
{
  static const char* value()
  {
    return DataType< ::map_mng::GetMaps >::value();
  }
  static const char* value(const ::map_mng::GetMapsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MNG_MESSAGE_GETMAPS_H
