// Generated by gencpp from file map_mng/GetMapsResponse.msg
// DO NOT EDIT!


#ifndef MAP_MNG_MESSAGE_GETMAPSRESPONSE_H
#define MAP_MNG_MESSAGE_GETMAPSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace map_mng
{
template <class ContainerAllocator>
struct GetMapsResponse_
{
  typedef GetMapsResponse_<ContainerAllocator> Type;

  GetMapsResponse_()
    : maps()  {
    }
  GetMapsResponse_(const ContainerAllocator& _alloc)
    : maps(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _maps_type;
  _maps_type maps;





  typedef boost::shared_ptr< ::map_mng::GetMapsResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::map_mng::GetMapsResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GetMapsResponse_

typedef ::map_mng::GetMapsResponse_<std::allocator<void> > GetMapsResponse;

typedef boost::shared_ptr< ::map_mng::GetMapsResponse > GetMapsResponsePtr;
typedef boost::shared_ptr< ::map_mng::GetMapsResponse const> GetMapsResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::map_mng::GetMapsResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::map_mng::GetMapsResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::map_mng::GetMapsResponse_<ContainerAllocator1> & lhs, const ::map_mng::GetMapsResponse_<ContainerAllocator2> & rhs)
{
  return lhs.maps == rhs.maps;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::map_mng::GetMapsResponse_<ContainerAllocator1> & lhs, const ::map_mng::GetMapsResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace map_mng

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::map_mng::GetMapsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::map_mng::GetMapsResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_mng::GetMapsResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::map_mng::GetMapsResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_mng::GetMapsResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::map_mng::GetMapsResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::map_mng::GetMapsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "58ee13666704003b145a48bfa86142f1";
  }

  static const char* value(const ::map_mng::GetMapsResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x58ee13666704003bULL;
  static const uint64_t static_value2 = 0x145a48bfa86142f1ULL;
};

template<class ContainerAllocator>
struct DataType< ::map_mng::GetMapsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "map_mng/GetMapsResponse";
  }

  static const char* value(const ::map_mng::GetMapsResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::map_mng::GetMapsResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] maps\n"
;
  }

  static const char* value(const ::map_mng::GetMapsResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::map_mng::GetMapsResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.maps);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GetMapsResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::map_mng::GetMapsResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::map_mng::GetMapsResponse_<ContainerAllocator>& v)
  {
    s << indent << "maps[]" << std::endl;
    for (size_t i = 0; i < v.maps.size(); ++i)
    {
      s << indent << "  maps[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.maps[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MAP_MNG_MESSAGE_GETMAPSRESPONSE_H
