// Generated by gencpp from file map_mng/MapGather.msg
// DO NOT EDIT!


#ifndef MAP_MNG_MESSAGE_MAPGATHER_H
#define MAP_MNG_MESSAGE_MAPGATHER_H

#include <ros/service_traits.h>


#include <map_mng/MapGatherRequest.h>
#include <map_mng/MapGatherResponse.h>


namespace map_mng
{

struct MapGather
{

typedef MapGatherRequest Request;
typedef MapGatherResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MapGather
} // namespace map_mng


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_mng::MapGather > {
  static const char* value()
  {
    return "64a91b5e5c6d91090d88bd8d7fda9226";
  }

  static const char* value(const ::map_mng::MapGather&) { return value(); }
};

template<>
struct DataType< ::map_mng::MapGather > {
  static const char* value()
  {
    return "map_mng/MapGather";
  }

  static const char* value(const ::map_mng::MapGather&) { return value(); }
};


// service_traits::MD5Sum< ::map_mng::MapGatherRequest> should match
// service_traits::MD5Sum< ::map_mng::MapGather >
template<>
struct MD5Sum< ::map_mng::MapGatherRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_mng::MapGather >::value();
  }
  static const char* value(const ::map_mng::MapGatherRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_mng::MapGatherRequest> should match
// service_traits::DataType< ::map_mng::MapGather >
template<>
struct DataType< ::map_mng::MapGatherRequest>
{
  static const char* value()
  {
    return DataType< ::map_mng::MapGather >::value();
  }
  static const char* value(const ::map_mng::MapGatherRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_mng::MapGatherResponse> should match
// service_traits::MD5Sum< ::map_mng::MapGather >
template<>
struct MD5Sum< ::map_mng::MapGatherResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_mng::MapGather >::value();
  }
  static const char* value(const ::map_mng::MapGatherResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_mng::MapGatherResponse> should match
// service_traits::DataType< ::map_mng::MapGather >
template<>
struct DataType< ::map_mng::MapGatherResponse>
{
  static const char* value()
  {
    return DataType< ::map_mng::MapGather >::value();
  }
  static const char* value(const ::map_mng::MapGatherResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MNG_MESSAGE_MAPGATHER_H
