// Generated by gencpp from file map_mng/SaveMap.msg
// DO NOT EDIT!


#ifndef MAP_MNG_MESSAGE_SAVEMAP_H
#define MAP_MNG_MESSAGE_SAVEMAP_H

#include <ros/service_traits.h>


#include <map_mng/SaveMapRequest.h>
#include <map_mng/SaveMapResponse.h>


namespace map_mng
{

struct SaveMap
{

typedef SaveMapRequest Request;
typedef SaveMapResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SaveMap
} // namespace map_mng


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::map_mng::SaveMap > {
  static const char* value()
  {
    return "e2f5b05fbc81352bcfb3bfeac378abe2";
  }

  static const char* value(const ::map_mng::SaveMap&) { return value(); }
};

template<>
struct DataType< ::map_mng::SaveMap > {
  static const char* value()
  {
    return "map_mng/SaveMap";
  }

  static const char* value(const ::map_mng::SaveMap&) { return value(); }
};


// service_traits::MD5Sum< ::map_mng::SaveMapRequest> should match
// service_traits::MD5Sum< ::map_mng::SaveMap >
template<>
struct MD5Sum< ::map_mng::SaveMapRequest>
{
  static const char* value()
  {
    return MD5Sum< ::map_mng::SaveMap >::value();
  }
  static const char* value(const ::map_mng::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_mng::SaveMapRequest> should match
// service_traits::DataType< ::map_mng::SaveMap >
template<>
struct DataType< ::map_mng::SaveMapRequest>
{
  static const char* value()
  {
    return DataType< ::map_mng::SaveMap >::value();
  }
  static const char* value(const ::map_mng::SaveMapRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::map_mng::SaveMapResponse> should match
// service_traits::MD5Sum< ::map_mng::SaveMap >
template<>
struct MD5Sum< ::map_mng::SaveMapResponse>
{
  static const char* value()
  {
    return MD5Sum< ::map_mng::SaveMap >::value();
  }
  static const char* value(const ::map_mng::SaveMapResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::map_mng::SaveMapResponse> should match
// service_traits::DataType< ::map_mng::SaveMap >
template<>
struct DataType< ::map_mng::SaveMapResponse>
{
  static const char* value()
  {
    return DataType< ::map_mng::SaveMap >::value();
  }
  static const char* value(const ::map_mng::SaveMapResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAP_MNG_MESSAGE_SAVEMAP_H
