(cl:defpackage map_mng-srv
  (:use )
  (:export
   "GETMAPS"
   "<GETMAPS-REQUEST>"
   "GETMAPS-REQUEST"
   "<GETMAPS-RESPONSE>"
   "GETMAPS-RESPONSE"
   "MAPGATHER"
   "<MAPGATHER-REQUEST>"
   "MAPGATHER-REQUEST"
   "<MAPGATHER-RESPONSE>"
   "MAPGATHER-RESPONSE"
   "SAVEMAP"
   "<SAVEMAP-REQUEST>"
   "SAVEMAP-REQUEST"
   "<SAVEMAP-RESPONSE>"
   "SAVEMAP-RESPONSE"
  ))

